# Generated by Django 5.2.3 on 2025-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, null=True)),
                ('org_address', models.CharField(max_length=100, null=True)),
                ('org_phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
